spring:
    application:
        name: EventReservationSystem
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5431/Biblio?createDatabaseIfNotExist=true
        username: Achraf
        password: dYLSm3s2JExbX6H6i6AnkqKeM3YO
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update